name: Build and Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  actions: read

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onefile --noconsole main.py

    - name: Archive build artifact
      run: |
        powershell -Command "if (!(Test-Path dist)) { mkdir dist }"
        move .\dist\main.exe dist\py-scrm.exe

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: py-scrm
        path: dist/py-scrm.exe

  release:
    needs: build
    runs-on: windows-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v5
      with:
        name: py-scrm

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        files: py-scrm.exe
        draft: false
        prerelease: false
